# Generated by Django 5.1.7 on 2025-04-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='djangoblog\x08log\\media'),
        ),
    ]
