# Generated by Django 5.1.7 on 2025-04-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='subject',
            new_name='title',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
    ]
