# Generated by Django 5.1.7 on 2025-04-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='midvote',
            field=models.IntegerField(default=0),
        ),
    ]
