# Generated by Django 5.1.7 on 2025-04-22 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_ratings_midvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='midvote',
        ),
    ]
